# Generated by Django 3.0.4 on 2020-04-13 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200413_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='kvk_num',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message="KVK number must be entered in the format: '12345678'. 8 digits long. Only registered businesses and foundations may advertise with FamilyHub", regex='^\\+?1?\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
